import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { getFirestore,doc,getDoc,collection,getDocs,getDocsFromServer,addDoc,setDoc,updateDoc,deleteDoc,serverTimestamp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";

const firebaseConfig={
 apiKey:"AIzaSyAzy2cwo5k47KcWevC9-_Nqejo4-fjoG9Y",
 authDomain:"blast-poin-hrr-253dc.firebaseapp.com",
 projectId:"blast-poin-hrr-253dc",
 storageBucket:"blast-poin-hrr-253dc.firebasestorage.app",
 messagingSenderId:"999695263332",
 appId:"1:999695263332:web:59241d6598e20d979ba171",
 measurementId:"G-XZ3HGP6C1J"
};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const SERVICES=[
 ["ac1","Pembersihan hingga 1 unit AC",99000],["ac2","Pembersihan hingga 2 unit AC",160000],["ac3","Pembersihan hingga 3 unit AC",240000],["ac4","Pembersihan hingga 4 unit AC",320000],["ac5","Pembersihan hingga 5 unit AC",400000],
 ["sofa1","Pembersihan sofa kain 1 seater",140000],["sofa2","Pembersihan sofa kain 2 seater",280000],["sofa3","Pembersihan sofa kain 3 seater",420000],["bed","Pembersihan sofa bed kain 1 unit",280000],
 ["m120","Pembersihan kasur 90/100/120 × 200 cm",180000],["m160","Pembersihan kasur 160 × 200 cm",220000],["m180","Pembersihan kasur 180/200 × 200 cm",300000]
];
let user=null,profile=null,customers=[],view="home",selected=new Set(),current=null,blastSearch="",dataSearch="",retensiSearch="";
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const cleanName=n=>String(n??"").replace(/(?:MAIL|-WA)$/i,"").trim();
const phoneClean=p=>String(p??"").replace(/\D/g,"");
const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const today=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
const dateKey=v=>{if(!v)return "";if(typeof v==="string")return v.slice(0,10);if(v?.toDate){const d=v.toDate();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}return String(v).slice(0,10)};
const fmtDate=v=>dateKey(v)||"-";
const customerRef=id=>doc(db,"users",user.uid,"customers",id);
const autoServices=points=>{const v=(Number(points)||0)*2500,ids=[];if(v>=99000)ids.push("ac"+(v>=400000?5:v>=320000?4:v>=240000?3:v>=160000?2:1));if(v>=420000)ids.push("sofa3");else if(v>=280000)ids.push("sofa2");else if(v>=140000)ids.push("sofa1");if(v>=280000)ids.push("bed");if(v>=180000)ids.push("m120");if(v>=220000)ids.push("m160");if(v>=300000)ids.push("m180");return ids};
const serviceText=ids=>ids.map(id=>SERVICES.find(s=>s[0]===id)?.[1]).filter(Boolean);
const messageFor=(c,ids)=>`Selamat siang Kak ${cleanName(c.name)},\n\nPerkenalkan saya ${profile?.senderName||"Ivan"} dari Informa. Mau menawarkan untuk Poin yang Kakak punya bisa di gunakan untuk jasa pembersihan dari Informa. Berikut beberapa pilihan yang bisa digunakan:\n\n${serviceText(ids).map((x,i)=>`${i+1}. ${x}`).join("\n")}\n\nMau saya bantu jadwalkan, Kak? Layanannya free, cukup tukar poin member 🙏`;
const followMessage=c=>`Selamat siang Kak ${cleanName(c.name)},\n\nSaya ${profile?.senderName||"Ivan"} dari Informa.\n\nIzin mengingatkan kembali terkait penawaran jasa pembersihan dari Informa yang sebelumnya saya sampaikan.\n\nJika Kakak masih berminat menggunakan layanannya, saya siap bantu proses dan jadwalkan ya Kak 🙏`;
const waUrl=(c,msg)=>`https://wa.me/${phoneClean(c.phone)}?text=${encodeURIComponent(msg)}`;
const normalizeStatus=s=>{const v=String(s??'').trim().toLowerCase();if(!v||v==='belum di blast')return 'Belum di Blast';if(v==='sudah di blast')return 'Sudah di Blast';if(v==='pending')return 'Pending';if(v==='transaksi')return 'Transaksi';return String(s).trim()||'Belum di Blast'};
const statusClass=s=>{const v=normalizeStatus(s);return v==="Belum di Blast"?"yellow":v==="Sudah di Blast"?"blue":v==="Pending"?"orange":v==="Transaksi"?"green":"gray"};
function shell(content){const n=profile?.senderName||profile?.username||"";return `<header class="top"><div class="toprow"><div><h1>Blast Poin HRR</h1><small>${esc(n)}</small></div><div class="topactions"><button class="btn mini" id="profileBtn">Profil</button><button class="btn mini" id="logoutBtn">Logout</button></div></div></header><main class="wrap">${content}</main>`}
function bindTop(){ $("profileBtn")?.addEventListener("click",profilePage); $("logoutBtn")?.addEventListener("click",async()=>{if(confirm("Yakin ingin logout?"))await signOut(auth)}); }
function login(){ $("app").innerHTML=`<div class="login"><div class="loginbox"><div class="logo">Blast Poin HRR</div><p class="muted center">Masuk untuk mengelola customer milik Anda.</p><label>Username</label><input id="username" autocomplete="username" placeholder="Masukkan username"><label>NIP</label><input id="nip" type="password" autocomplete="current-password" placeholder="Masukkan NIP"><button class="btn primary full" id="loginBtn">Masuk</button><div id="loginMsg" class="notice hidden"></div></div></div>`;$('loginBtn').onclick=async()=>{const u=$('username').value.trim().toLowerCase(),p=$('nip').value;if(!u||!p)return showLogin('Username dan NIP wajib diisi.');try{await signInWithEmailAndPassword(auth,`${u}@blastpoinhrr.app`,p)}catch(e){showLogin(e?.code==='auth/invalid-credential'||e?.code==='auth/wrong-password'||e?.code==='auth/user-not-found'?'Login gagal. Username atau NIP tidak cocok.':e?.message||'Login gagal.')}}}
function showLogin(t){$('loginMsg').textContent=t;$('loginMsg').classList.remove('hidden')}
async function loadProfile(){const s=await getDoc(doc(db,"users",user.uid));profile=s.exists()?s.data():{username:user.email?.split("@")[0]||"admin",senderName:"Ivan"}}
async function loadCustomers(forceServer=false){const ref=collection(db,"users",user.uid,"customers");const s=forceServer?await getDocsFromServer(ref):await getDocs(ref);customers=s.docs.map(d=>{const raw=d.data();const rawStatus=raw.status??raw.Status??raw.statusCustomer??raw.blastStatus??"";return {id:d.id,...raw,status:normalizeStatus(rawStatus)}});customers.sort((a,b)=>cleanName(a.name).localeCompare(cleanName(b.name),"id"))}
function counts(){return {all:customers.length,belum:customers.filter(c=>normalizeStatus(c.status)==='Belum di Blast').length,sudah:customers.filter(c=>normalizeStatus(c.status)==='Sudah di Blast').length,pending:customers.filter(c=>normalizeStatus(c.status)==='Pending').length,transaksi:customers.filter(c=>normalizeStatus(c.status)==='Transaksi').length}}
function home(){const c=counts();$('app').innerHTML=shell(`<div class="grid homegrid"><button class="card menu" id="data"><div class="ico">👥</div><span>Datacustomer</span><b>${c.all}</b></button><button class="card menu" id="add"><div class="ico">➕</div><span>+ Customer</span></button><button class="card menu" id="blast"><div class="ico">💬</div><span>Blast Poin</span><b>${c.belum}</b></button><button class="card menu" id="follow"><div class="ico">🔁</div><span>Follow Up Poin</span></button><button class="card menu" id="retensi"><div class="ico">⭐</div><span>Retensi</span></button></div><div class="card"><b>Status customer</b><div class="stats"><button class="stat yellow" id="sBelum"><b>${c.belum}</b><span>Belum di Blast</span></button><button class="stat blue" id="sSudah"><b>${c.sudah}</b><span>Sudah di Blast</span></button><button class="stat orange" id="sPending"><b>${c.pending}</b><span>Pending</span></button><button class="stat green" id="sTrans"><b>${c.transaksi}</b><span>Transaksi</span></button></div></div>`);bindTop();$('data').onclick=dataPage;$('add').onclick=addMenu;$('blast').onclick=blastPage;$('follow').onclick=followPage;$('retensi').onclick=retensiPage;$('sBelum').onclick=()=>statusPage('Belum di Blast');$('sSudah').onclick=()=>statusPage('Sudah di Blast');$('sPending').onclick=()=>statusPage('Pending');$('sTrans').onclick=()=>statusPage('Transaksi')}
function backBtn(fn){return `<button class="btn ghost" id="back">Kembali</button>`}
function statusPage(status){const list=customers.filter(c=>normalizeStatus(c.status)===status);$('app').innerHTML=shell(`<div class="row between"><div class="title">${status}</div>${backBtn(home)}</div>${list.map(customerCard).join('')||empty('Tidak ada customer dengan status ini.')}`);bindTop();$('back').onclick=home}
function customerCard(c){return `<div class="customer"><div class="row between"><div><h3>${esc(cleanName(c.name))}</h3><p class="muted">${esc(c.member||'')} · ${esc(c.phone||'')}</p></div><span class="status ${statusClass(c.status||'Belum di Blast')}">${esc(c.status||'Belum di Blast')}</span></div><div class="row between smallline"><span>${esc(c.points||0)} poin · ${rupiah((Number(c.points)||0)*2500)}</span><span>${c.lastBlastAt?fmtDate(c.lastBlastAt):''}</span></div><button class="btn ghost full" data-detail="${c.id}">Detail / Edit</button></div>`}
function dataPage(){const q=dataSearch.toLowerCase();const list=customers.filter(c=>[c.name,c.member,c.phone].some(x=>String(x??'').toLowerCase().includes(q)));$('app').innerHTML=shell(`<div class="row between"><div class="title">Datacustomer</div>${backBtn(home)}</div><input id="dataSearch" placeholder="Cari nama, member, nomor..." value="${esc(dataSearch)}"><div class="row wraprow tools"><span class="badge">Total ${customers.length}</span><button class="btn secondary" id="addOne">+ Customer</button><button class="btn secondary" id="import">Add Data Excel</button><button class="btn secondary" id="copy">Add Data Copy</button></div>${list.map(customerCard).join('')||empty('Belum ada customer.')}`);bindTop();$('back').onclick=home;$('dataSearch').oninput=e=>{dataSearch=e.target.value;dataPage()};$('addOne').onclick=()=>addForm();$('import').onclick=()=>importPage('customer');$('copy').onclick=()=>copyCustomerPage('customer');document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>addForm(customers.find(x=>x.id===b.dataset.detail)))}
function empty(t){return `<div class="card muted center">${esc(t)}</div>`}
function addMenu(){$('app').innerHTML=shell(`<div class="row between"><div class="title">+ Customer</div>${backBtn(home)}</div><div class="bigmenu"><button class="card menu" id="a"><div class="ico">📝</div><span>Add Data</span></button><button class="card menu" id="i"><div class="ico">📊</div><span>Add Data Excel</span></button><button class="card menu" id="c"><div class="ico">📋</div><span>Add Data Copy</span></button></div>`);bindTop();$('back').onclick=home;$('a').onclick=()=>addForm();$('i').onclick=()=>importPage('customer');$('c').onclick=()=>copyCustomerPage('customer')}
function addForm(c=null){const edit=!!c;$('app').innerHTML=shell(`<div class="row between"><div class="title">${edit?'Edit Customer':'Add Data'}</div>${backBtn(dataPage)}</div><div class="card"><label>Member</label><input id="member" value="${esc(c?.member||'')}"><label>Nama</label><input id="name" value="${esc(c?.name||'')}"><label>No HP</label><input id="phone" inputmode="tel" value="${esc(c?.phone||'')}"><label>Poin</label><input id="points" type="number" value="${esc(c?.points??'')}"><button class="btn primary full topgap" id="save">${edit?'Simpan Perubahan':'Simpan Customer'}</button>${edit?`<button class="btn danger full topgap8" id="del">Hapus Customer</button>`:''}</div>`);bindTop();$('back').onclick=dataPage;$('save').onclick=async()=>{const obj={member:$('member').value.trim(),name:$('name').value.trim(),phone:phoneClean($('phone').value),points:Number($('points').value)||0,status:c?.status||'Belum di Blast',blastCount:Number(c?.blastCount)||0,blastDate:c?.blastDate||'',followUpDone:!!c?.followUpDone,updatedAt:serverTimestamp()};if(!obj.name||!obj.phone)return alert('Nama dan nomor HP wajib diisi.');if(edit)await updateDoc(customerRef(c.id),obj);else await addDoc(collection(db,'users',user.uid,'customers'),{...obj,createdAt:serverTimestamp()});await loadCustomers();dataPage()};if(edit)$('del').onclick=async()=>{if(confirm('Hapus customer ini?')){await deleteDoc(customerRef(c.id));await loadCustomers();dataPage()}}}
function importPage(returnTo='customer'){$('app').innerHTML=shell(`<div class="row between"><div class="title">Add Data Excel</div>${backBtn(returnTo==='customer'?addMenu:dataPage)}</div><div class="card"><p class="muted">Pilih file Excel. Kolom yang dikenali: Member, Nama, No HP/Phone, Poin/Jumlah.</p><input id="file" type="file" accept=".xlsx,.xls,.csv"><button class="btn primary full topgap" id="read">Baca File</button><div id="preview"></div></div>`);bindTop();$('back').onclick=returnTo==='customer'?addMenu:dataPage;$('read').onclick=async()=>{const f=$('file').files[0];if(!f)return alert('Pilih file terlebih dahulu.');const data=await f.arrayBuffer();const wb=XLSX.read(data,{type:'array'});const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const parsed=parseRows(rows);showImportPreview(parsed,'customer',returnTo)}}
function parseRows(rows){return rows.map(r=>{const keys=Object.keys(r);const val=(names)=>{const k=keys.find(x=>names.some(n=>String(x).toLowerCase().replace(/[^a-z0-9]/g,'').includes(n)));return k?r[k]:''};return {member:String(val(['member','kode'])).trim(),name:cleanName(val(['nama','name','customer'])),phone:phoneClean(val(['nohp','phone','telepon','nomor'])),points:Number(val(['poin','points','jumlah']))||0}}).filter(x=>x.name&&x.phone)}
function showImportPreview(rows,type='customer',returnTo='customer'){$('preview').innerHTML=`<hr><p><b>${rows.length}</b> data siap disimpan.</p><div class="preview">${rows.slice(0,30).map((r,i)=>`<div>${i+1}. ${esc(r.name)} · ${esc(r.phone)} · ${esc(r.points)} poin</div>`).join('')}</div><button class="btn primary full topgap" id="saveImport">Simpan Semua</button>`;$('saveImport').onclick=async()=>{if(!rows.length)return;let n=0;for(const r of rows){await addDoc(collection(db,'users',user.uid,'customers'),{...r,status:'Belum di Blast',blastCount:0,blastDate:'',followUpDone:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});n++}await loadCustomers();alert(`${n} customer berhasil disimpan.`);returnTo==='customer'?dataPage():home()}}
function copyCustomerPage(returnTo='customer'){ $('app').innerHTML=shell(`<div class="row between"><div class="title">Add Data Copy</div>${backBtn(returnTo==='customer'?addMenu:dataPage)}</div><div class="card"><p class="muted">Tempel data tabel dari Excel. Contoh: Member | NamaMAIL | No HP | Poin. Bisa banyak customer sekaligus.</p><textarea id="paste" placeholder="IR03368493\tDAUD KIANO IMANUEL SITUMORANGMAIL\t6281112114411\t130"></textarea><button class="btn primary full topgap" id="parse">Preview Data</button><div id="preview"></div></div>`);bindTop();$('back').onclick=returnTo==='customer'?addMenu:dataPage;$('parse').onclick=()=>{const rows=parseCopiedCustomer($('paste').value);showImportPreview(rows,'customer',returnTo)}}
function parseCopiedCustomer(text){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);return lines.map(line=>{let a=line.split(/\t/);if(a.length<3)a=line.split(/\s{2,}/);if(a.length<3)return null;let member=a[0]||'',name=a[1]||'',phone='',points=0;for(let i=2;i<a.length;i++){if(/\d{8,}/.test(String(a[i])))phone=phoneClean(a[i]);else if(!points&&/\d+/.test(String(a[i])))points=Number(String(a[i]).replace(/\D/g,''))||0}return {member:String(member).trim(),name:cleanName(name),phone,points}}).filter(x=>x&&x.name&&x.phone)}
async function blastPage(){blastSearch="";await loadCustomers(true);const list=customers.filter(c=>normalizeStatus(c.status)==='Belum di Blast'&&[c.name,c.member,c.phone].some(x=>String(x??'').toLowerCase().includes(blastSearch.toLowerCase())));$('app').innerHTML=shell(`<div class="row between"><div><div class="title">Blast Poin</div><div class="muted">Hanya customer dengan status Belum di Blast.</div></div>${backBtn(home)}</div><input id="blastSearch" placeholder="Cari customer..." value="${esc(blastSearch)}"><div class="row wraprow tools"><span class="status yellow">Belum di Blast: ${list.length}</span></div>${list.map(c=>`<div class="customer"><div class="row between"><div><h3>${esc(cleanName(c.name))}</h3><p class="muted">${esc(c.phone)} · ${esc(c.points||0)} poin · ${rupiah((Number(c.points)||0)*2500)}</p></div></div><button class="btn primary full" data-blast="${c.id}">Buka Blast</button></div>`).join('')||empty('Tidak ada customer yang belum di-blast.')}`);bindTop();$('back').onclick=home;$('blastSearch').oninput=e=>{blastSearch=e.target.value;blastPage()};document.querySelectorAll('[data-blast]').forEach(b=>b.onclick=()=>blastDetail(customers.find(x=>x.id===b.dataset.blast)))}
function blastDetail(c){selected=new Set(autoServices(c.points));let msg=messageFor(c,[...selected]);$('app').innerHTML=shell(`<div class="row between"><div class="title">Blast Poin</div>${backBtn(blastPage)}</div><div class="card"><h2>${esc(cleanName(c.name))}</h2><p class="muted">${esc(c.phone)} · ${esc(c.points||0)} poin · Nilai ${rupiah((Number(c.points)||0)*2500)}</p><div class="row wraprow"><button class="btn secondary" id="auto">Pilih Otomatis</button><button class="btn ghost" id="clear">Kosongkan</button></div><div id="services">${serviceControls()}</div><hr><label>Pesan WhatsApp</label><textarea id="msg">${esc(msg)}</textarea><a class="wa" id="wa" href="${waUrl(c,msg)}" target="_blank">Buka WhatsApp & Kirim</a><button class="btn primary full topgap" id="mark">Tandai Sudah Blast</button><p class="muted smallline">Setelah pesan benar-benar dikirim di WhatsApp, tekan “Tandai Sudah Blast”.</p></div>`);bindTop();$('back').onclick=blastPage;bindService(c);$('msg').oninput=e=>$('wa').href=waUrl(c,e.target.value);$('auto').onclick=()=>{selected=new Set(autoServices(c.points));renderServiceArea(c)};$('clear').onclick=()=>{selected.clear();renderServiceArea(c)};$('mark').onclick=async()=>{if(!selected.size)return alert('Pilih minimal satu layanan.');const now=today();await updateDoc(customerRef(c.id),{status:'Sudah di Blast',blastDate:now,lastBlastAt:serverTimestamp(),blastCount:(Number(c.blastCount)||0)+1,lastBlastServices:[...selected],followUpDone:false,updatedAt:serverTimestamp()});await loadCustomers();blastPage()}}
function serviceControls(){return SERVICES.map(s=>`<label class="service"><input type="checkbox" data-service="${s[0]}" ${selected.has(s[0])?'checked':''}><span><b>${esc(s[1])}</b><small>${rupiah(s[2])}</small></span></label>`).join('')}
function renderServiceArea(c){$('services').innerHTML=serviceControls();const msg=messageFor(c,[...selected]);$('msg').value=msg;$('wa').href=waUrl(c,msg);bindService(c)}
function bindService(c){document.querySelectorAll('[data-service]').forEach(i=>i.onchange=()=>{if(i.checked)selected.add(i.dataset.service);else selected.delete(i.dataset.service);const msg=messageFor(c,[...selected]);$('msg').value=msg;$('wa').href=waUrl(c,msg)})}
function followUpList(){const t=today();return customers.filter(c=>{const s=normalizeStatus(c.status);return (s==='Sudah di Blast'||s==='Pending')&&c.blastDate&&dateKey(c.blastDate)<t&&!c.followUpDone&&s!=='Transaksi'})}
function followPage(){const list=followUpList();$('app').innerHTML=shell(`<div class="row between"><div><div class="title">Follow Up Poin</div><div class="muted">Muncul mulai hari berikutnya setelah blast.</div></div>${backBtn(home)}</div><div class="row wraprow tools"><span class="badge">${list.length} customer</span></div>${list.map(c=>`<div class="customer"><div class="row between"><div><h3>${esc(cleanName(c.name))}</h3><p class="muted">${esc(c.phone)} · Blast ${fmtDate(c.blastDate)}</p></div><span class="status ${statusClass(c.status||'Sudah di Blast')}">${esc(c.status||'Sudah di Blast')}</span></div><button class="btn primary full" data-follow="${c.id}">Follow Up</button></div>`).join('')||empty('Belum ada customer yang perlu di-follow up.')}`);bindTop();$('back').onclick=home;document.querySelectorAll('[data-follow]').forEach(b=>b.onclick=()=>followDetail(customers.find(x=>x.id===b.dataset.follow)))}
function followDetail(c){const msg=followMessage(c);$('app').innerHTML=shell(`<div class="row between"><div class="title">Follow Up Poin</div>${backBtn(followPage)}</div><div class="card"><h2>${esc(cleanName(c.name))}</h2><p class="muted">${esc(c.phone)} · Status ${esc(c.status||'')}</p><textarea id="msg">${esc(msg)}</textarea><a class="wa" id="wa" href="${waUrl(c,msg)}" target="_blank">Buka WhatsApp</a><button class="btn secondary full topgap" id="pending">Tandai Pending</button><button class="btn primary full topgap8" id="trans">Tandai Transaksi</button><button class="btn ghost full topgap8" id="done">Tandai Follow Up Selesai</button></div>`);bindTop();$('back').onclick=followPage;$('msg').oninput=e=>$('wa').href=waUrl(c,e.target.value);$('pending').onclick=()=>setPending(c);$('trans').onclick=()=>transactionForm(c);$('done').onclick=async()=>{await updateDoc(customerRef(c.id),{followUpDone:true,lastFollowUpAt:serverTimestamp(),updatedAt:serverTimestamp()});await loadCustomers();followPage()}}
async function setPending(c){await updateDoc(customerRef(c.id),{status:'Pending',updatedAt:serverTimestamp()});await loadCustomers();followPage()}
function transactionForm(c){$('app').innerHTML=shell(`<div class="row between"><div class="title">Catat Transaksi Comser</div>${backBtn(()=>followDetail(c))}</div><div class="card"><h3>${esc(cleanName(c.name))}</h3><p class="muted">${esc(c.phone)}</p><label>Tanggal Transaksi</label><input id="td" type="date" value="${today()}"><label>Pilihan Jasa</label><select id="service"><option value="">Pilih jasa</option>${SERVICES.map(s=>`<option value="${s[0]}">${esc(s[1])}</option>`).join('')}</select><label>Tanggal Pengerjaan</label><input id="work" type="date" value="${today()}"><button class="btn primary full topgap" id="save">Simpan Transaksi</button></div>`);bindTop();$('back').onclick=()=>followDetail(c);$('save').onclick=async()=>{if(!$('service').value)return alert('Pilih jasa terlebih dahulu.');const hist=Array.isArray(c.comserHistory)?c.comserHistory:[];hist.push({tanggalTransaksi:$('td').value,pilihanJasa:$('service').value,tanggalPengerjaan:$('work').value,createdAt:new Date().toISOString()});await updateDoc(customerRef(c.id),{status:'Transaksi',comserHistory:hist,transactionDate:$('td').value,updatedAt:serverTimestamp()});await loadCustomers();retensiPage('comser')}}
function retensiPage(tab='dashboard'){if(tab==='dashboard'){ $('app').innerHTML=shell(`<div class="row between"><div class="title">Retensi</div>${backBtn(home)}</div><div class="bigmenu"><button class="card menu" id="rs"><div class="ico">👤</div><span>Retensi Saya</span></button><button class="card menu" id="rc"><div class="ico">🧹</div><span>Retensi Comser</span></button><button class="card menu" id="br"><div class="ico">📣</div><span>Blast Retensi</span></button></div>`);bindTop();$('back').onclick=home;$('rs').onclick=()=>retensiPage('saya');$('rc').onclick=()=>retensiPage('comser');$('br').onclick=()=>retensiPage('blast');return}if(tab==='saya')return retensiSayaPage();if(tab==='comser')return retensiComserPage();return blastRetensiPage()}
function retensiSayaPage(){const list=customers.filter(c=>Array.isArray(c.retensiHistory)||c.retensiOwner);$('app').innerHTML=shell(`<div class="row between"><div class="title">Retensi Saya</div>${backBtn(()=>retensiPage())}</div><div class="tools row wraprow"><button class="btn primary" id="addRS">+ Tambah Customer</button><input id="rsearch" placeholder="Cari nama / nomor..." value="${esc(retensiSearch)}"></div>${list.map(c=>`<div class="customer"><div class="row between"><div><h3>${esc(cleanName(c.name))}</h3><p class="muted">${esc(c.phone)}</p></div><span class="badge">${Array.isArray(c.retensiHistory)?c.retensiHistory.length:0} transaksi</span></div><button class="btn secondary full" data-rs="${c.id}">History / Follow Up</button></div>`).join('')||empty('Belum ada customer Retensi Saya.')}`);bindTop();$('back').onclick=()=>retensiPage();$('addRS').onclick=()=>retensiSayaForm();$('rsearch').oninput=e=>{retensiSearch=e.target.value.toLowerCase();retensiSayaPage()};document.querySelectorAll('[data-rs]').forEach(b=>b.onclick=()=>retensiSayaDetail(customers.find(c=>c.id===b.dataset.rs)))}
function retensiSayaForm(c=null){const edit=!!c;$('app').innerHTML=shell(`<div class="row between"><div class="title">${edit?'Tambah Transaksi':'Tambah Customer Retensi'}</div>${backBtn(()=>retensiPage('saya'))}</div><div class="card">${edit?`<p><b>${esc(cleanName(c.name))}</b><br><span class="muted">${esc(c.phone)}</span></p>`:`<label>Nama Customer</label><input id="name"><label>No. HP</label><input id="phone" inputmode="tel">`}<label>No. Receipt</label><input id="receipt"><label>Tanggal Transaksi</label><input id="date" type="date" value="${today()}"><label>Value Transaksi</label><input id="value" type="number"><label>Barang yang Dibeli</label><input id="item"><button class="btn primary full topgap" id="save">Simpan</button></div>`);bindTop();$('back').onclick=()=>retensiPage('saya');$('save').onclick=async()=>{let name=edit?c.name:$('name').value.trim(),phone=edit?c.phone:phoneClean($('phone').value);if(!name||!phone)return alert('Nama dan No. HP wajib diisi.');const h={noReceipt:$('receipt').value.trim(),tanggalTransaksi:$('date').value,valueTransaksi:Number($('value').value)||0,barang:$('item').value.trim(),createdAt:new Date().toISOString()};if(edit){const hist=Array.isArray(c.retensiHistory)?c.retensiHistory:[];hist.push(h);await updateDoc(customerRef(c.id),{retensiHistory:hist,retensiOwner:true,updatedAt:serverTimestamp()})}else{await addDoc(collection(db,'users',user.uid,'customers'),{member:'',name,phone,points:0,status:'Retensi Saya',retensiOwner:true,retensiHistory:[h],createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}await loadCustomers();retensiSayaPage()}}
function retensiSayaDetail(c){const hist=Array.isArray(c.retensiHistory)?c.retensiHistory:[],msg=followMessage(c);$('app').innerHTML=shell(`<div class="row between"><div class="title">History Retensi</div>${backBtn(()=>retensiPage('saya'))}</div><div class="card"><h3>${esc(cleanName(c.name))}</h3><p class="muted">${esc(c.phone)}</p></div>${hist.map((h,i)=>`<div class="customer"><b>Transaksi ${i+1}</b><p class="muted">${esc(h.tanggalTransaksi||'-')} · Receipt: ${esc(h.noReceipt||'-')}</p><p>${esc(h.barang||'-')} · ${rupiah(h.valueTransaksi||0)}</p></div>`).join('')||empty('Belum ada history.')}<button class="btn secondary full" id="addTx">+ Tambah Transaksi</button><textarea id="msg" class="topgap">${esc(msg)}</textarea><a class="wa" id="wa" href="${waUrl(c,msg)}" target="_blank">Follow Up</a>`);bindTop();$('back').onclick=()=>retensiPage('saya');$('addTx').onclick=()=>retensiSayaForm(c);$('msg').oninput=e=>$('wa').href=waUrl(c,e.target.value)}
function blastRetensiPage(){loadBlastRetensi().then(list=>{$('app').innerHTML=shell(`<div class="row between"><div class="title">Blast Retensi</div>${backBtn(()=>retensiPage())}</div><div class="tools row wraprow"><button class="btn primary" id="addBR">+ Tambah Customer</button><button class="btn secondary" id="impBR">Customer Excel</button><button class="btn secondary" id="copyBR">Customer Copy</button></div>${list.map(c=>`<div class="customer"><div class="row between"><div><h3>${esc(cleanName(c.name))}</h3><p class="muted">${esc(c.phone)}</p></div><span class="status ${c.blasted?'blue':'yellow'}">${c.blasted?'Sudah Blast Retensi':'Belum Blast Retensi'}</span></div><button class="btn ${c.blasted?'secondary':'primary'} full" data-br="${c.id}">${c.blasted?'Buka / Follow Up':'Blast Retensi'}</button></div>`).join('')||empty('Belum ada customer Blast Retensi.')}`);bindTop();$('back').onclick=()=>retensiPage();$('addBR').onclick=()=>blastRetensiForm();$('impBR').onclick=()=>blastRetensiImport();$('copyBR').onclick=()=>blastRetensiCopy();document.querySelectorAll('[data-br]').forEach(b=>b.onclick=()=>blastRetensiDetail(list.find(x=>x.id===b.dataset.br)))})}
async function loadBlastRetensi(){const s=await getDocs(collection(db,'users',user.uid,'blastRetensi'));return s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>cleanName(a.name).localeCompare(cleanName(b.name),'id'))}
function blastRetensiForm(){ $('app').innerHTML=shell(`<div class="row between"><div class="title">Tambah Customer Retensi</div>${backBtn(()=>retensiPage('blast'))}</div><div class="card"><label>Nama Customer</label><input id="name"><label>No. HP</label><input id="phone" inputmode="tel"><button class="btn primary full topgap" id="save">Simpan Customer</button></div>`);bindTop();$('back').onclick=()=>retensiPage('blast');$('save').onclick=async()=>{const name=$('name').value.trim(),phone=phoneClean($('phone').value);if(!name||!phone)return alert('Nama dan No. HP wajib diisi.');await addDoc(collection(db,'users',user.uid,'blastRetensi'),{name,phone,blasted:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});blastRetensiPage()}}
function blastRetensiImport(){ $('app').innerHTML=shell(`<div class="row between"><div class="title">Customer Excel</div>${backBtn(()=>retensiPage('blast'))}</div><div class="card"><input id="file" type="file" accept=".xlsx,.xls,.csv"><button class="btn primary full topgap" id="read">Baca File</button><div id="preview"></div></div>`);bindTop();$('back').onclick=()=>retensiPage('blast');$('read').onclick=async()=>{const f=$('file').files[0];if(!f)return alert('Pilih file.');const b=await f.arrayBuffer(),wb=XLSX.read(b,{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}).map(r=>({name:cleanName(r.Nama||r.Name||r.Customer||Object.values(r)[0]||''),phone:phoneClean(r['No HP']||r.Phone||r.Telepon||Object.values(r)[1]||'')})).filter(x=>x.name&&x.phone);blastRetensiPreview(rows)}}
function blastRetensiCopy(){ $('app').innerHTML=shell(`<div class="row between"><div class="title">Customer Copy</div>${backBtn(()=>retensiPage('blast'))}</div><div class="card"><p class="muted">Tempel Nama dan No HP, satu customer per baris. Bisa dipisahkan TAB.</p><textarea id="paste" placeholder="Nama Customer\t62812xxxx"></textarea><button class="btn primary full topgap" id="parse">Preview Data</button><div id="preview"></div></div>`);bindTop();$('back').onclick=()=>retensiPage('blast');$('parse').onclick=()=>{const rows=$('paste').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const a=line.split(/\t|\s{2,}/);return {name:cleanName(a[0]||''),phone:phoneClean(a.find(x=>/\d{8,}/.test(x))||'')}}).filter(x=>x.name&&x.phone);blastRetensiPreview(rows)}}
function blastRetensiPreview(rows){$('preview').innerHTML=`<hr><p><b>${rows.length}</b> data siap disimpan.</p>${rows.slice(0,30).map((r,i)=>`<div>${i+1}. ${esc(r.name)} · ${esc(r.phone)}</div>`).join('')}<button class="btn primary full topgap" id="save">Simpan Semua</button>`;$('save').onclick=async()=>{for(const r of rows)await addDoc(collection(db,'users',user.uid,'blastRetensi'),{...r,blasted:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});blastRetensiPage()}}
function blastRetensiDetail(c){const msg=followMessage(c);$('app').innerHTML=shell(`<div class="row between"><div class="title">Blast Retensi</div>${backBtn(()=>retensiPage('blast'))}</div><div class="card"><h2>${esc(cleanName(c.name))}</h2><p class="muted">${esc(c.phone)}</p><textarea id="msg">${esc(msg)}</textarea><a class="wa" id="wa" href="${waUrl(c,msg)}" target="_blank">Buka WhatsApp</a><button class="btn primary full topgap" id="done">Tandai Sudah Blast Retensi</button></div>`);bindTop();$('back').onclick=()=>retensiPage('blast');$('msg').oninput=e=>$('wa').href=waUrl(c,e.target.value);$('done').onclick=async()=>{await updateDoc(doc(db,'users',user.uid,'blastRetensi',c.id),{blasted:true,lastBlastAt:serverTimestamp(),updatedAt:serverTimestamp()});blastRetensiPage()}}
function retensiComserPage(){const list=customers.filter(c=>normalizeStatus(c.status)==='Transaksi');$('app').innerHTML=shell(`<div class="row between"><div class="title">Retensi Comser</div>${backBtn(()=>retensiPage())}</div><div class="muted">Customer dengan status Transaksi masuk otomatis ke sini.</div>${list.map(c=>`<div class="customer"><div class="row between"><div><h3>${esc(cleanName(c.name))}</h3><p class="muted">${esc(c.phone)} · ${(c.comserHistory||[]).length} transaksi</p></div><span class="status green">Transaksi</span></div><button class="btn secondary full" data-cs="${c.id}">History / Follow Up</button></div>`).join('')||empty('Belum ada transaksi Comser.')}`);bindTop();$('back').onclick=()=>retensiPage();document.querySelectorAll('[data-cs]').forEach(b=>b.onclick=()=>retensiComserDetail(customers.find(x=>x.id===b.dataset.cs)))}
function retensiComserDetail(c){const hist=Array.isArray(c.comserHistory)?c.comserHistory:[],msg=followMessage(c);$('app').innerHTML=shell(`<div class="row between"><div class="title">Retensi Comser</div>${backBtn(()=>retensiPage('comser'))}</div><div class="card"><h3>${esc(cleanName(c.name))}</h3><p class="muted">${esc(c.phone)}</p></div>${hist.map((h,i)=>{const s=SERVICES.find(x=>x[0]===h.pilihanJasa);return `<div class="customer"><b>Transaksi ${i+1}</b><p class="muted">Tanggal transaksi: ${esc(h.tanggalTransaksi||'-')}</p><p>Jasa: ${esc(s?.[1]||h.pilihanJasa||'-')}</p><p>Tanggal pengerjaan: ${esc(h.tanggalPengerjaan||'-')}</p></div>`}).join('')||empty('Belum ada history.')}<textarea id="msg">${esc(msg)}</textarea><a class="wa" id="wa" href="${waUrl(c,msg)}" target="_blank">Follow Up</a></div>`);bindTop();$('back').onclick=()=>retensiPage('comser');$('msg').oninput=e=>$('wa').href=waUrl(c,e.target.value)}
function profilePage(){$('app').innerHTML=shell(`<div class="row between"><div class="title">Profil Saya</div>${backBtn(home)}</div><div class="card"><label>Username</label><input value="${esc(profile?.username||user?.email?.split('@')[0]||'')}" disabled><label>Nama Pengirim</label><input id="sender" value="${esc(profile?.senderName||'Ivan')}"><p class="muted">NIP digunakan sebagai password Firebase Authentication dan tidak disimpan di Firestore.</p><button class="btn primary full" id="save">Simpan</button></div>`);bindTop();$('back').onclick=home;$('save').onclick=async()=>{await updateDoc(doc(db,'users',user.uid),{senderName:$('sender').value.trim()||'Ivan'});await loadProfile();home()}}
onAuthStateChanged(auth,async u=>{user=u;if(!u){login();return}try{await loadProfile();await loadCustomers();home()}catch(e){console.error(e);$('app').innerHTML=`<div class="login"><div class="loginbox"><b>Gagal memuat data Firebase.</b><p class="muted">${esc(e.message)}</p><button class="btn primary full" onclick="location.reload()">Coba Lagi</button></div></div>`}});
